env:
  global:
  - REPO_DIR=muLFC
  - BUILD_COMMIT=78c8fd1d22e1aba8beb732cf8ffcf9da30c86295
  - BUILD_DEPENDS="numpy"
  - TEST_DEPENDS="numpy"
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
  - secure: MNKyBWOzu7JAUmC0Y+JhPKfytXxY/ADRmUIMEWZV977FLZPgYctqd+lqel2QIFgdHDO1CIdTSymOOFZckM9ICUXg9Ta+8oBjSvAVWO1ahDcToRM2DLq66fKg+NKimd2OfK7x597h/QmUSl4k8XyvyyXgl5jOiLg/EJxNE2r83IA=
language: python
python: 3.5
sudo: required
dist: trusty
services: docker
matrix:
  exclude:
  - python: 3.5
  include:
  - os: linux
    env: MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.4
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.4
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=2.7
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=3.4
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=3.5
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=pypy-5.7
before_install:
- ls && pwd
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- build_wheel $REPO_DIR $PLAT
- ls && pwd && ls /home/travis/build/bonfus/muLFC-wheels/wheelhouse/
script:
- install_run $PLAT
before_deploy:
- export RELEASE_PKG_FILE=$(ls /home/travis/build/bonfus/muLFC-wheels/wheelhouse)
- echo "deploying $RELEASE_PKG_FILE to Packagecloud releases"
- pwd

deploy:
  provider: packagecloud
  repository: wheels
  username: muLFC
  skip_cleanup: true
  local-dir: /home/travis/build/bonfus/muLFC-wheels/wheelhouse
  package_glob: "*.whl"
  token: ${PACKAGECLOUD_TOKEN}
