env:
  global:
  - REPO_DIR=muLFC
  - BUILD_COMMIT=78c8fd1d22e1aba8beb732cf8ffcf9da30c86295
  - BUILD_DEPENDS="numpy"
  - TEST_DEPENDS="numpy"
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
  - secure: MNKyBWOzu7JAUmC0Y+JhPKfytXxY/ADRmUIMEWZV977FLZPgYctqd+lqel2QIFgdHDO1CIdTSymOOFZckM9ICUXg9Ta+8oBjSvAVWO1ahDcToRM2DLq66fKg+NKimd2OfK7x597h/QmUSl4k8XyvyyXgl5jOiLg/EJxNE2r83IA=
language: python
python: 3.5
sudo: required
dist: trusty
services: docker
matrix:
  exclude:
  - python: 3.5
  include:
  - os: linux
    env: MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.4
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.4
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=2.7
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=3.4
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=3.5
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    #    language: generic
    env:
    - MB_PYTHON_VERSION=pypy-5.7
before_install:
- ls && pwd
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- build_wheel $REPO_DIR $PLAT
- ls && pwd && ls /home/travis/build/bonfus/muLFC-wheels/wheelhouse/
script:
- install_run $PLAT
before_deploy:
- export RELEASE_PKG_DIR=$(ls /home/travis/build/bonfus/muLFC-wheels/wheelhouse)
- echo "deploying $RELEASE_PKG_DIR to GitHub releases"
- cd "${RELEASE_PKG_FILE}"
- ls

deploy:
  provider: packagecloud
  repository: wheels
  username: packagecloud@bnf.33mail.com
  skip_cleanup: true
  local-dir: /home/travis/build/bonfus/muLFC-wheels/wheelhouse
  package_glob: "*.whl"
  token:
    secure: ZbdW3nYmUBaU2DBhIUUBYWPcDP5NkUMSUeEmd/aQHxgBErpKdtjs5CRp9c2bXTamshs8lyXy0TicS8DsVpD9I797AxuPF7xzLPaJOsw5KrKhmdRv1rrbANHi9hnkHl4bWFldTzh/AwdWZinrk8Lt7G/zEa/oLD1ICsfXPKhZ5z5crH/17a+DjXFfbt7y3oNsmlv3KAWLa25VnEtuSnqr4Ab7a4veOWNVO4RPDMkCmlMW5d/mEykLNjrNTgVnTuUZ5B9mReE6aWDBEV+unanEjPWDVgY+GS9n2NRxcCmCRhVEz3JUsrz0y0TXl/qGRXaJJShDN0GE6xKp2x2SI9EuCswLxhHNxp0+1BXkx9GP7Ngoj+bTnq/Z0cxZ0uVFtUYe2mnchyuv4w0ZNWnLVpwHKKamRVtap1d2TNWWnx5LjomKFA4e1THAFPWrmGLn0welbBSGF8FZepdcjpcMTsb55GlI7SQ59LNuW7OWG2Z/C4euq4uFMbF135bybv6Su5WUwM2YvsiDaNcb9nKui62RbSO0NA1Ntth8hQbsqhVYTb4WHH45kBqk57ngvbRLwMjm10QEOugbSNjbj3HXQMyWaoHHkFzDIDzJFUyasgXeJQjIIOoC4499NbooN8+v73PCRnWzVvHGBzhvSbZf8rGrzKKM5LEaLpzq0u4Drj1ciMY=
