language: python
python: 3.5

env:
  global:
  - REPO_DIR=muLFC
  - BUILD_COMMIT=567485f5ab21339a80499655a5317653dfe5c9e7
  - BUILD_DEPENDS="numpy"
  - TEST_DEPENDS="numpy"
  - PLAT=x86_64
  - UNICODE_WIDTH=32
sudo: required
dist: trusty
services: docker
matrix:
  exclude:
  - python: 3.5
  include:
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - PLAT=i686
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.4
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.4
    - PLAT=i686
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
    - PLAT=i686
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - PLAT=i686
#  - os: osx
#    #    language: generic
#    env:
#    - MB_PYTHON_VERSION=2.7
#  - os: osx
#    #    language: generic
#    env:
#    - MB_PYTHON_VERSION=3.4
#  - os: osx
#    #    language: generic
#    env:
#    - MB_PYTHON_VERSION=3.5
#  - os: osx
#    #    language: generic
#    env:
#    - MB_PYTHON_VERSION=3.6
#  - os: osx
#    #    language: generic
#    env:
#    - MB_PYTHON_VERSION=pypy-5.7
before_install:
- ls && pwd
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- build_wheel $REPO_DIR $PLAT
- ls && pwd && ls /home/travis/build/bonfus/muLFC-wheels/wheelhouse/
script:
- install_run $PLAT
before_deploy:
- export RELEASE_PKG_FILE=$(ls /home/travis/build/bonfus/muLFC-wheels/wheelhouse)
- echo "deploying $RELEASE_PKG_FILE to Packagecloud releases"
- pwd

deploy:
  provider: pypi
  user: pietro.bonfa
  skip_cleanup: true
  password:
    secure: "O8YpDBTTWCxMFSekcXRH7PRaEMxdP6rP1OS74ZPgsMhg6IvV0/PapwadGV1qZrb88qY/WcFCa8s4NsiKluoAmvPQuvz3kGYMorbpptJ2ZfsHJRmbtGWdw3uys7O+IGP0jv/QlglOc8DKV1rjXvubqA+zjL3ejIT+L4UHthVwmT5LeJN309pxCpnpvViTuGQM4hxg1Mh4oNuxfbEOo8TSyaje+OQNtCiMx4ctV/6tTmaAu9k0N5zyZCdz2wpbUIVOv6delWyddF9TldQazQ4mmeJQcsl1S501oYUgwsKbtidrRukW2j0hrJeGg0mGzT/KakvWhwqaHdPsI00YeN1htZQnucGo0j7Isz+mUWfzP/CnRFgEckSSDgexkZxGFir4pfEw+xtt256YW3gv8M4x0jHLMg5sUTZsBes0HidKqs9Dq5wl6EaKlnJjGk+DCkuJemAVMLUEQOb6piB+dOWB+0Yy81psCyKfri8k6iBU+KHxxwPSbJ1Ut8IStk1tumvtuly8r4q+0OMLmtI783tdyqpbkeQSMYnq6sUIImiysjTvSwJY0FYbAw8vwAUbv76jOhfUlM14LzShVMLR/i5DdLRqfQGNdu5AIj5PYVK7G7L636tdmEli8iyDsNB4yS7uQy8186iGGacEAzlmFgbT0tf3OUKfrpq92Uzhf1WpUdY="
  server: https://test.pypi.org/legacy/
  distributions: "bdist_wheel"
